
language: python

git:
    depth: 1

matrix:
    include:
        - python: "2.7"
          os: linux
          env:
              - WITH_QT_TEST=False

        - python: "3.4"
          os: linux
          env:
              - WITH_QT_TEST=False

        - python: "3.5"
          os: linux
          env:
              - WITH_QT_TEST=True

#virtualenv:
#    system_site_packages: NO !!!
# the system python and the one from travis have been compiled with different options

addons:
  apt:
    packages:
      # Only used by the DISTRIB="ubuntu" setting
      - libhdf5-7
      - libhdf5-dev
      - gfortran
      - libatlas-base-dev
      - libqtcore4
#For OpenCL:
      - python-cffi
      - python3-cffi
      - ocl-icd-libopencl1
      - opencl-headers
      - python-pyopencl
      - python3-pyopencl
# command to install dependencies

before_install:
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then . ./ci/before_install-linux.sh; fi"
#  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]; then . ./ci/travis/before_install-osx.sh; fi"

install:
  - "python ci/info_platform.py"
  - "pip install --upgrade pip"
  - "pip install cython"
  - "pip install --upgrade numpy"
  - "pip install --upgrade h5py"  
  - "pip install --upgrade -r ci/requirements_travis.txt"
  - "python ci/info_platform.py"
  - "python setup.py build"
  - "python setup.py bdist_wheel"
  - "pip install --pre --no-index --find-links dist/ pyFAI"

before_script:
    # Start X Virtual Framebuffer useful for GUI testing
    # Doc: https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
    - if [ "$TRAVIS_OS_NAME" == "linux" ];
      then
          export DISPLAY=:99.0;
          sh -e /etc/init.d/xvfb start;
          sleep 3;
      fi

# command to run tests
script:
  - "python setup.py test"
  - "python ./run_tests.py -m --installed"
