os:
  - linux
#  - osx

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
#virtualenv:
#    system_site_packages: NO !!!
# the system python and the one from travis have been compiled with different options

addons:
  apt:
    packages:
      # Only used by the DISTRIB="ubuntu" setting
      - libhdf5-7
      - libhdf5-dev
      - gfortran
      - libatlas-base-dev
      - libqtcore4
#For OpenCL:
      - libboost-python1.54.0
      - libboost-python1.54-dev
      - opencl-headers
      - python-pyopencl
# command to install dependencies

before_install:
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then . ./ci/before_install-linux.sh; fi"
#  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]; then . ./ci/travis/before_install-osx.sh; fi"

install:
  - "python ci/info_platform.py"
  - "pip install --upgrade pip"
  - "pip install cython --trusted-host www.edna-site.org --find-links http://www.edna-site.org/pub/wheelhouse"
  - "pip install --upgrade numpy --trusted-host www.edna-site.org --find-links http://www.edna-site.org/pub/wheelhouse"
    #remove after h5py 2.6
  - "pip install --upgrade h5py --trusted-host www.edna-site.org --find-links http://www.edna-site.org/pub/wheelhouse --no-index"  
  - "pip install --upgrade --trusted-host www.edna-site.org -r ci/requirements_travis.txt"
  - "python ci/info_platform.py"
  - "python setup.py build"
  - "python setup.py bdist_wheel"
  - "pip install --pre --no-index --find-links dist/ pyFAI"

# command to run tests
script:
  - "python setup.py test"
  - "python ./run_tests.py -m --installed"
